### PR TITLE
modify: jib config to support shared services release

### PR DESCRIPTION
**Pull request by hwatkins-ch**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by aduffy-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by hwatkins-ch** [comment]
Don't merge yet -> We don't want to trigger pipelines

- [ ] Wait for confirmation we can merge

**Review by foman-ch — APPROVED** [review]

**Comment by hwatkins-ch** [comment]
Will reopen once the current deployment to live has gone through

**Pull request closed without merging**
